// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebKhachSan.Models;

#nullable disable

namespace WebKhachSan.Migrations
{
    [DbContext(typeof(QuanLyKhachSanContext))]
    [Migration("20260331103428_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebKhachSan.Models.CtdatPhong", b =>
                {
                    b.Property<string>("MaDatPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaLoaiPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("GiaTamTinh")
                        .HasColumnType("float");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDatPhong", "MaLoaiPhong")
                        .HasName("PK__CTDatPho__01748CCB2826D9B7");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("CTDatPhong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.CthoaDon", b =>
                {
                    b.Property<string>("MaCthd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCTHD");

                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("SoTien")
                        .HasColumnType("float");

                    b.HasKey("MaCthd")
                        .HasName("PK__CTHoaDon__1E4FA771C49770B6");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("CTHoaDon", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.CtthuePhong", b =>
                {
                    b.Property<string>("MaThuePhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("GiaThueTaiThoiDiem")
                        .HasColumnType("float");

                    b.HasKey("MaThuePhong", "MaPhong")
                        .HasName("PK__CTThuePh__EA527D9DC71494CE");

                    b.HasIndex("MaPhong");

                    b.ToTable("CTThuePhong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.DatPhong", b =>
                {
                    b.Property<string>("MaDatPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNhanDuKien")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTraDuKien")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDatPhong")
                        .HasName("PK__DatPhong__6344ADEA8C00C577");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DatPhong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.GiaPhong", b =>
                {
                    b.Property<string>("MaGia")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("MaLoaiPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaGia")
                        .HasName("PK__GiaPhong__3CD3DE5E82ED75AC");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("GiaPhong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaThuePhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("date");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B84974548");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaThuePhong");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E5360820A4");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoaiPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int?>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaLoaiPhong")
                        .HasName("PK__LoaiPhon__23021217BD3EC184");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA474981CB5D");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaLoaiPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SoPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaPhong")
                        .HasName("PK__Phong__20BD5E5B29621A33");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C652953631F21");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.ThuePhong", b =>
                {
                    b.Property<string>("MaThuePhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThuePhong")
                        .HasName("PK__ThuePhon__4859A8781FEF241D");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("ThuePhong", (string)null);
                });

            modelBuilder.Entity("WebKhachSan.Models.CtdatPhong", b =>
                {
                    b.HasOne("WebKhachSan.Models.DatPhong", "MaDatPhongNavigation")
                        .WithMany("CtdatPhongs")
                        .HasForeignKey("MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK_CTDP_DatPhong");

                    b.HasOne("WebKhachSan.Models.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("CtdatPhongs")
                        .HasForeignKey("MaLoaiPhong")
                        .IsRequired()
                        .HasConstraintName("FK_CTDP_LoaiPhong");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaLoaiPhongNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.CthoaDon", b =>
                {
                    b.HasOne("WebKhachSan.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("CthoaDons")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK_CTHD_HoaDon");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.CtthuePhong", b =>
                {
                    b.HasOne("WebKhachSan.Models.Phong", "MaPhongNavigation")
                        .WithMany("CtthuePhongs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK_CTTP_Phong");

                    b.HasOne("WebKhachSan.Models.ThuePhong", "MaThuePhongNavigation")
                        .WithMany("CtthuePhongs")
                        .HasForeignKey("MaThuePhong")
                        .IsRequired()
                        .HasConstraintName("FK_CTTP_ThuePhong");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaThuePhongNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.DatPhong", b =>
                {
                    b.HasOne("WebKhachSan.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK_DatPhong_KhachHang");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.GiaPhong", b =>
                {
                    b.HasOne("WebKhachSan.Models.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("GiaPhongs")
                        .HasForeignKey("MaLoaiPhong")
                        .HasConstraintName("FK_GiaPhong_LoaiPhong");

                    b.Navigation("MaLoaiPhongNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.HoaDon", b =>
                {
                    b.HasOne("WebKhachSan.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.HasOne("WebKhachSan.Models.ThuePhong", "MaThuePhongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaThuePhong")
                        .HasConstraintName("FK_HoaDon_ThuePhong");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaThuePhongNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.NhanVien", b =>
                {
                    b.HasOne("WebKhachSan.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("FK_NhanVien_TaiKhoan");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.Phong", b =>
                {
                    b.HasOne("WebKhachSan.Models.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .HasConstraintName("FK__Phong__MaLoaiPho__3D5E1FD2");

                    b.Navigation("MaLoaiPhongNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.ThuePhong", b =>
                {
                    b.HasOne("WebKhachSan.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("ThuePhongs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK_ThuePhong_KhachHang");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("WebKhachSan.Models.DatPhong", b =>
                {
                    b.Navigation("CtdatPhongs");
                });

            modelBuilder.Entity("WebKhachSan.Models.HoaDon", b =>
                {
                    b.Navigation("CthoaDons");
                });

            modelBuilder.Entity("WebKhachSan.Models.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");

                    b.Navigation("ThuePhongs");
                });

            modelBuilder.Entity("WebKhachSan.Models.LoaiPhong", b =>
                {
                    b.Navigation("CtdatPhongs");

                    b.Navigation("GiaPhongs");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("WebKhachSan.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebKhachSan.Models.Phong", b =>
                {
                    b.Navigation("CtthuePhongs");
                });

            modelBuilder.Entity("WebKhachSan.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebKhachSan.Models.ThuePhong", b =>
                {
                    b.Navigation("CtthuePhongs");

                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
